# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    paydunya.private_key: '%env(PAYDUNYA_PRIVATE_KEY)%'
    paydunya.public_key: '%env(PAYDUNYA_PUBLIC_KEY)%'
    paydunya.token: '%env(PAYDUNYA_TOKEN)%'
    paydunya.mode: '%env(PAYDUNYA_MODE)%'
    app.url: '%env(APP_URL)%'
    orange_sms.api_key: '%env(default::ORANGE_SMS_API_KEY)%'
    twilio.account_sid: '%env(default::TWILIO_ACCOUNT_SID)%'
    twilio.auth_token: '%env(default::TWILIO_AUTH_TOKEN)%'
    twilio.phone_number: '%env(default::TWILIO_PHONE_NUMBER)%'
# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies
        autoconfigure: true # Automatically applies certain tags
        bind:
            $projectDir: '%kernel.project_dir%'   # injection de projectDir
            $paydunyaMasterKey: '%env(PAYDUNYA_MASTER_KEY)%'
            $paydunyaPrivateKey: '%env(PAYDUNYA_PRIVATE_KEY)%'
            $paydunyaPublicKey: '%env(PAYDUNYA_PUBLIC_KEY)%'
            $paydunyaToken: '%env(PAYDUNYA_TOKEN)%'
            $paydunyaMode: '%env(PAYDUNYA_MODE)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Définition explicite du PaymentService pour injections complexes
    App\Service\PaymentService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $httpClient: '@http_client'
            $pdfGenerator: '@App\Service\PdfGenerator'
            $em: '@doctrine.orm.entity_manager'
            $urlGenerator: '@router.default'
            $slugger: '@slugger'

    App\Service\QRCodeService: ~
    Endroid\QrCode\Writer\PngWriter: ~

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    # Endroid\QrCode\Builder\PngBuilder:
    #     arguments:
    #         $writer: '@Endroid\QrCode\Writer\PngWriter'

    App\Factory\QrCodeBuilderFactory: ~

    Endroid\QrCodeBundle\Twig\QrCodeExtension:
        tags: ['twig.extension']

    # Notification service configuration
    App\Service\NotificationChannelService:
        arguments:
            $orangeSmsApiKey: '%orange_sms.api_key%'
            $twilioAccountSid: '%twilio.account_sid%'
            $twilioAuthToken: '%twilio.auth_token%'
            $twilioPhoneNumber: '%twilio.phone_number%'

    App\Factory\QrCodeBuilderFactory:
        public: true

